name: custom-model
description: カスタムモデルデータの追加リクエスト
title: "[カスタムモデル] "
labels: ["add-model"]
body:
  - type: markdown
    attributes:
      value: |
        ## カスタムモデルデータのリクエスト
        以下のフォームに入力すると、自動的にリソースパックにカスタムモデルが追加されます。
        
        **注意事項:**
        - 画像URLは直接アクセス可能な公開URLを指定してください
        - PNG形式の画像のみ対応しています
        - エラーが発生した場合、このIssueは自動的にクローズされます
        - Issueの編集では再実行されません。エラーの場合は新しいIssueを作成してください
  
  - type: input
    id: materials
    attributes:
      label: マテリアル
      description: "カンマ区切りのマテリアルリスト（例: diamond_axe,iron_sword,golden_hoe）"
      placeholder: "diamond_axe,iron_sword"
    validations:
      required: true
  
  - type: input
    id: custom_model_data
    attributes:
      label: カスタムモデルデータ名
      description: "英小文字、数字、アンダースコアのみ使用可能（例: my_custom_model）"
      placeholder: "my_custom_model"
    validations:
      required: true
  
  - type: input
    id: image_url
    attributes:
      label: 画像URL
      description: "PNG画像ファイルの直接URL（Imgur、Discord添付など）"
      placeholder: "https://example.com/my_texture.png"
    validations:
      required: true

  - type: input
    id: frametime
    attributes:
      label: Frametime（アニメーション用・任意）
      description: "アニメーションテクスチャの場合のみ指定。1フレームあたりのtick数（例: 1, 2, 5）。画像は縦に複数フレームを並べた形式にしてください。"
      placeholder: "1"
    validations:
      required: false

  - type: textarea
    id: notes
    attributes:
      label: 補足事項
      description: "このカスタムモデルに関する追加情報（任意）"
    validations:
      required: false
