name: add-model3d
description: 3Dカスタムモデルデータの追加リクエスト
title: "[3Dモデル] "
labels: ["add-model3d"]
body:
  - type: markdown
    attributes:
      value: |
        ## 3Dカスタムモデルデータのリクエスト
        以下のフォームに入力すると、自動的にリソースパックに3Dカスタムモデルが追加されます。
        
        **注意事項:**
        - 各URLは直接アクセス可能な公開URLを指定してください
        - モデルはBlockbenchなどで作成したJSON形式、テクスチャはPNG形式のみ対応しています
        - エラーが発生した場合、このIssueは自動的にクローズされます
  
  - type: input
    id: materials
    attributes:
      label: マテリアル
      description: "カンマ区切りのマテリアルリスト（例: diamond_axe,iron_sword）"
      placeholder: "diamond_axe,iron_sword"
    validations:
      required: true
  
  - type: input
    id: custom_model_data
    attributes:
      label: カスタムモデルデータ名
      description: "英小文字、数字、アンダースコアのみ使用可能（例: my_custom_model）"
      placeholder: "my_custom_model"
    validations:
      required: true

  - type: input
    id: model_json_url
    attributes:
      label: モデルJSONのURL
      description: "モデルJSONファイルの直接URL"
      placeholder: "https://example.com/my_model.json"
    validations:
      required: true

  - type: textarea
    id: layer_image_urls
    attributes:
      label: レイヤー画像のURLリスト
      description: "モデルJSON内のテクスチャ定義（`0`, `1`, ...）に対応するPNG画像のURLを、改行区切りで順番通りに貼り付けてください。"
      placeholder: |
        https://example.com/texture_0.png
        https://example.com/texture_1.png
        https://example.com/texture_2.png
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: 補足事項
      description: "このカスタムモデルに関する追加情報（任意）"
    validations:
      required: false
