name: Add Custom Model Data

on:
  workflow_dispatch:
    inputs:
      materials:
        description: "Materials (comma-separated, e.g., diamond_axe,iron_sword)"
        required: true
        type: string
      custom_model_data:
        description: "Custom model data name (optional, defaults to image filename)"
        required: false
        type: string
      image_url:
        description: "URL to the image file"
        required: true
        type: string

jobs:
  add-custom-model:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Download image
        run: |
          IMAGE_NAME=$(basename "${{ inputs.image_url }}")
          curl -L -o "$IMAGE_NAME" "${{ inputs.image_url }}"
          echo "IMAGE_FILE=$IMAGE_NAME" >> $GITHUB_ENV

      - name: Build tool
        run: cargo build --release

      - name: Run processor
        run: |
          MATERIALS="${{ inputs.materials }}"
          CUSTOM_MODEL_DATA="${{ inputs.custom_model_data }}"

          # Split materials by comma and build arguments
          ARGS=""
          IFS=',' read -ra MATERIAL_ARRAY <<< "$MATERIALS"
          for material in "${MATERIAL_ARRAY[@]}"; do
            material=$(echo "$material" | xargs)  # trim whitespace
            ARGS="$ARGS -m $material"
          done

          # Add custom model data if provided
          if [ -n "$CUSTOM_MODEL_DATA" ]; then
            ARGS="$ARGS -c $CUSTOM_MODEL_DATA"
          fi

          # Run the processor
          ./target/release/processer $ARGS "$IMAGE_FILE"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "Add custom model data for ${{ inputs.materials }}"
          title: "Add custom model data: ${{ inputs.custom_model_data || env.IMAGE_FILE }}"
          body: |
            ## Custom Model Data Addition

            - **Materials**: ${{ inputs.materials }}
            - **Custom Model Data**: ${{ inputs.custom_model_data || 'Auto-generated from filename' }}
            - **Image**: ${{ inputs.image_url }}

            This PR was automatically generated by the workflow.
          branch: custom-model/${{ inputs.custom_model_data || github.run_id }}
          delete-branch: true
