name: 🎨 2Dモデルを追加

on:
  issues:
    types: [opened]

jobs:
  call-reusable-workflow:
    if: contains(github.event.issue.labels.*.name, 'add-model')
    uses: ./.github/workflows/reusable-process-issue.yml
    with:
      issue-type: 'model'
      issue-body: ${{ github.event.issue.body }}
      issue-number: ${{ github.event.issue.number }}
      actor: ${{ github.actor }}
      actor-id: ${{ github.actor_id }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}