name: Add Custom Model Data

on:
  workflow_dispatch:
    inputs:
      materials:
        description: "Materials (comma-separated, e.g., diamond_axe,iron_sword)"
        required: true
        type: string
      custom_model_data:
        description: "Custom model data name (lowercase, numbers, underscores only)"
        required: true
        type: string
      image_url:
        description: "URL to the image file"
        required: true
        type: string

jobs:
  add-custom-model:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Download image
        run: |
          IMAGE_NAME="${{ inputs.custom_model_data }}.png"
          
          # Download with curl
          HTTP_CODE=$(curl -L -w "%{http_code}" -o "$IMAGE_NAME" "${{ inputs.image_url }}")
          
          # Check if download was successful
          if [ "$HTTP_CODE" -ne 200 ]; then
            echo "Error: Failed to download image. HTTP status: $HTTP_CODE"
            rm -f "$IMAGE_NAME"
            exit 1
          fi
          
          # Verify it's actually a PNG file
          if ! file "$IMAGE_NAME" | grep -q "PNG image"; then
            echo "Error: Downloaded file is not a valid PNG image"
            cat "$IMAGE_NAME" | head -5
            rm -f "$IMAGE_NAME"
            exit 1
          fi
          
          echo "IMAGE_FILE=$IMAGE_NAME" >> $GITHUB_ENV

      - name: Build tool
        run: cargo build --release

      - name: Run processor
        run: |
          MATERIALS="${{ inputs.materials }}"
          CUSTOM_MODEL_DATA="${{ inputs.custom_model_data }}"

          # Split materials by comma and build arguments
          ARGS=""
          IFS=',' read -ra MATERIAL_ARRAY <<< "$MATERIALS"
          for material in "${MATERIAL_ARRAY[@]}"; do
            material=$(echo "$material" | xargs)  # trim whitespace
            ARGS="$ARGS -m $material"
          done

          # Run the processor
          ./target/release/processer $ARGS -c "$CUSTOM_MODEL_DATA" "$IMAGE_FILE"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Add custom model data for ${{ inputs.materials }}"
          title: "Add custom model data: ${{ inputs.custom_model_data }}"
          body: |
            ## Custom Model Data Addition

            - **Materials**: ${{ inputs.materials }}
            - **Custom Model Data**: ${{ inputs.custom_model_data }}
            - **Image**: ${{ inputs.image_url }}

            This PR was automatically generated by the workflow.
          branch: custom-model/${{ inputs.custom_model_data }}
          delete-branch: true
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
